version: '3.7'
services:
  dev-env:
    build: 
      context: .
    network_mode: service:dev-db
    volumes:
      - ../../:/workspaces:cached
    command: sleep infinity
  dev-db:
    image: mcr.microsoft.com/mssql/server:latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password!123
    ports:
      - 1433:1433